"""initial_schema

Revision ID: d39055272e4d
Revises: 
Create Date: 2025-10-03 16:26:36.386745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd39055272e4d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etp_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_structure', sa.Text(), nullable=True),
    sa.Column('default_content', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('structured_content', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('sections', sa.Text(), nullable=True),
    sa.Column('processing_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    op.create_table('legal_norm_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('norm_urn', sa.String(length=500), nullable=False),
    sa.Column('norm_label', sa.String(length=1000), nullable=False),
    sa.Column('sphere', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source_json', sa.Text(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('legal_norm_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legal_norm_cache_norm_urn'), ['norm_urn'], unique=True)
        batch_op.create_index(batch_op.f('ix_legal_norm_cache_sphere'), ['sphere'], unique=False)
        batch_op.create_index(batch_op.f('ix_legal_norm_cache_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('documents_generated', sa.Integer(), nullable=True),
    sa.Column('chat_messages_sent', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('etp_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('answers', sa.Text(), nullable=True),
    sa.Column('answers_validated', sa.Boolean(), nullable=True),
    sa.Column('necessity', sa.Text(), nullable=True),
    sa.Column('conversation_stage', sa.String(length=50), nullable=True),
    sa.Column('requirements_json', sa.Text(), nullable=True),
    sa.Column('generated_etp', sa.Text(), nullable=True),
    sa.Column('preview_content', sa.Text(), nullable=True),
    sa.Column('preview_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('messages', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('necessity', sa.Text(), nullable=True),
    sa.Column('conversation_stage', sa.String(length=50), nullable=True),
    sa.Column('requirements_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['etp_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('analysis_result', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['etp_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kb_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('etp_id', sa.Integer(), nullable=True),
    sa.Column('objective_slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['etp_id'], ['etp_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kb_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kb_document_objective_slug'), ['objective_slug'], unique=False)

    op.create_table('kb_chunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kb_document_id', sa.Integer(), nullable=False),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('objective_slug', sa.String(length=100), nullable=False),
    sa.Column('citations_json', sa.Text(), nullable=True),
    sa.Column('embedding', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kb_document_id'], ['kb_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kb_chunk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kb_chunk_kb_document_id'), ['kb_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kb_chunk_objective_slug'), ['objective_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_kb_chunk_section_type'), ['section_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kb_chunk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kb_chunk_section_type'))
        batch_op.drop_index(batch_op.f('ix_kb_chunk_objective_slug'))
        batch_op.drop_index(batch_op.f('ix_kb_chunk_kb_document_id'))

    op.drop_table('kb_chunk')
    with op.batch_alter_table('kb_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kb_document_objective_slug'))

    op.drop_table('kb_document')
    op.drop_table('document_analyses')
    op.drop_table('chat_sessions')
    op.drop_table('etp_sessions')
    op.drop_table('users')
    with op.batch_alter_table('legal_norm_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legal_norm_cache_status'))
        batch_op.drop_index(batch_op.f('ix_legal_norm_cache_sphere'))
        batch_op.drop_index(batch_op.f('ix_legal_norm_cache_norm_urn'))

    op.drop_table('legal_norm_cache')
    op.drop_table('knowledge_base')
    op.drop_table('etp_templates')
    # ### end Alembic commands ###
